import 'package:flutter/material.dart';

extension InputDexoration on InputDecoration {
  InputDecoration copyFrom(
      {Widget? icon,
      Color? iconColor,
      Widget? label,
      String? labelText,
      TextStyle? floatingLabelStyle,
      String? helperText,
      TextStyle? helperStyle,
      int? helperMaxLines,
      String? hintText,
      TextStyle? hintStyle,
      TextDirection? hintTextDirection,
      int? hintMaxLines,
      Widget? error,
      String? errorText,
      TextStyle? errorStyle,
      int? errorMaxLines,
      FloatingLabelAlignment? floatingLabelAlignment,
      bool? isCollapsed,
      bool? isDense,
      EdgeInsetsGeometry? contentPadding,
      Widget? prefixIcon,
      Widget? prefix,
      String? prefixText,
      BoxConstraints? prefixIconConstraints,
      TextStyle? prefixStyle,
      Color? prefixIconColor,
      Widget? suffixIcon,
      Widget? suffix,
      String? suffixText,
      TextStyle? suffixStyle,
      Color? suffixIconColor,
      BoxConstraints? suffixIconConstraints,
      Widget? counter,
      String? counterText,
      TextStyle? counterStyle,
      Color? focusColor,
      Color? hoverColor,
      InputBorder? focusedErrorBorder,
      bool? enabled,
      String? semanticCounterText,
      bool? alignLabelWithHint,
      BoxConstraints? constraints}) {
    return InputDecoration(
      border: border,
      disabledBorder: disabledBorder,
      enabledBorder: enabledBorder,
      focusedBorder: focusedBorder,
      errorBorder: errorBorder,
      contentPadding: this.contentPadding,
      filled: filled,
      fillColor: fillColor,
      floatingLabelBehavior: floatingLabelBehavior,
//
      icon: icon ?? this.icon,
      iconColor: iconColor ?? this.iconColor,
      label: label ?? this.label,
      labelText: labelText ?? this.labelText,
      labelStyle: labelStyle,
      floatingLabelStyle: floatingLabelStyle ?? this.floatingLabelStyle,
      helperText: helperText ?? this.helperText,
      helperStyle: helperStyle ?? this.helperStyle,
      helperMaxLines: helperMaxLines ?? this.helperMaxLines,
      hintText: hintText ?? this.hintText,
      hintStyle: hintStyle ?? this.hintStyle,
      hintTextDirection: hintTextDirection ?? this.hintTextDirection,
      hintMaxLines: hintMaxLines ?? this.hintMaxLines,
      error: error ?? this.error,
      errorText: errorText ?? this.errorText,
      errorStyle: errorStyle ?? this.errorStyle,
      errorMaxLines: errorMaxLines ?? this.errorMaxLines,
      floatingLabelAlignment: floatingLabelAlignment ?? this.floatingLabelAlignment,
      isCollapsed: isCollapsed ?? this.isCollapsed,
      isDense: isDense ?? this.isDense,
      prefixIcon: prefixIcon ?? this.prefixIcon,
      prefix: prefix ?? this.prefix,
      prefixText: prefixText ?? this.prefixText,
      prefixStyle: prefixStyle ?? this.prefixStyle,
      prefixIconColor: prefixIconColor ?? this.prefixIconColor,
      prefixIconConstraints: prefixIconConstraints ?? this.prefixIconConstraints,
      suffixIcon: suffixIcon ?? this.suffixIcon,
      suffix: suffix ?? this.suffix,
      suffixText: suffixText ?? this.suffixText,
      suffixStyle: suffixStyle ?? this.suffixStyle,
      suffixIconColor: suffixIconColor ?? this.suffixIconColor,
      suffixIconConstraints: suffixIconConstraints ?? this.suffixIconConstraints,
      counter: counter ?? this.counter,
      counterText: counterText ?? this.counterText,
      counterStyle: counterStyle ?? this.counterStyle,
      focusColor: focusColor ?? this.focusColor,
      hoverColor: hoverColor ?? this.hoverColor,
      focusedErrorBorder: focusedErrorBorder ?? this.focusedErrorBorder,
      enabled: enabled ?? this.enabled,
      semanticCounterText: semanticCounterText ?? this.semanticCounterText,
      alignLabelWithHint: alignLabelWithHint ?? this.alignLabelWithHint,
      constraints: constraints ?? this.constraints,
    );
  }
}
