name: form_plus
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  country_pickers: ^2.0.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3

  form_builder_validators: ^9.1.0
  form_builder_extra_fields: ^10.1.0
  form_builder_file_picker: ^4.1.0
  form_builder_cupertino_fields: ^0.2.1
  get: ^4.6.6
  form_builder_phone_field: ^2.0.1
  flutter_form_builder: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
